version: "3.8"

services:
  local-stack-aws:
    image: localstack/localstack:3
    networks:
      - hmpps
    container_name: local-stack-aws-vsip-orc
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"

networks:
  hmpps:
