version: "3"
services:
  hmpps-manage-prison-visits-orchestration:
    build:
      context: .
    container_name: hmpps-manage-prison-visits-orchestration
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      - SYSTEM_CLIENT_ID=book-a-prison-visit-client
      - SYSTEM_CLIENT_SECRET=clientsecret

  localstack:
    image: localstack/localstack:1.3
    networks:
      - hmpps
    container_name: localstack-external-vsip-orc
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "8090:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/auth/health" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  visit-scheduler:
    image: quay.io/hmpps/visit-scheduler:latest
    networks:
      - hmpps
    container_name: visit-scheduler
    ports:
      - "8081:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      - PRISON_API_URL=https://prison-api-dev.prison.service.justice.gov.uk
      - PRISONER_OFFENDER_SEARCH_URL=https://prisoner-search-dev.prison.service.justice.gov.uk
      - SYSTEM_CLIENT_ID=book-a-prison-visit-client
      - SYSTEM_CLIENT_SECRET=clientsecret
      - SPRING_DATASOURCE_URL=jdbc:postgresql://visit-scheduler-db:5432/visit_scheduler
      - FEATURE_EVENTS_SNS_ENABLED=false

  visit-scheduler-db:
    image: postgres:13.2
    networks:
      - hmpps
    container_name: visit-scheduler-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=visit_scheduler
      - POSTGRES_USER=visit_scheduler
      - POSTGRES_DB=visit_scheduler

networks:
  hmpps:
