version: "3"
services:
  hmpps-manage-prison-visits-orchestration:
    build:
      context: .
    network_mode: "host"
    container_name: hmpps-manage-prison-visits-orchestration
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  localstack:
    image: localstack/localstack:1.3
    networks:
      - hmpps
    container_name: localstack-external-vsip-orc
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"

networks:
  hmpps:
