package uk.gov.justice.digital.hmpps.hmppsmanageprisonvisitsorchestration.dto.visit.allocation.enums

@Suppress("unused")
enum class VisitOrderHistoryType {
  MIGRATION,
  VO_ACCUMULATION,
  VO_ALLOCATION,
  VO_AND_PVO_ALLOCATION,
  PVO_ALLOCATION,
  VO_EXPIRATION,
  VO_AND_PVO_EXPIRATION,
  PVO_EXPIRATION,
  ALLOCATION_USED_BY_VISIT,
  ALLOCATION_REFUNDED_BY_VISIT_CANCELLED,
  PRISONER_BALANCE_RESET,
  SYNC_FROM_NOMIS,
  ALLOCATION_ADDED_AFTER_PRISONER_MERGE,
  ADMIN_RESET_NEGATIVE_BALANCE,
  MANUAL_PRISONER_BALANCE_ADJUSTMENT,
}
