version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@8

parameters:
  alerts-slack-channel:
    type: string
    default: prison-visit-booking-alerts
  releases-slack-channel:
    type: string
    default: prison-visit-booking-alerts

jobs:
  acceptance_tests_main:
    docker:
      - image: maven:3.9.5-eclipse-temurin-21
      - image: seleniarm/standalone-chromium
        environment:
          CHROME_HEADLESS: 1
    circleci_ip_ranges: true

    steps:
      - run:
          name: Checkout VSIP UI Tests
          command: git clone https://github.com/ministryofjustice/hmpps-vsip-ui-tests.git
      - run:
          name: get git status
          command: |
            cd hmpps-vsip-ui-tests
            git checkout main
            git pull
            git status
      - run:
          name: Change to project directory then clean install
          command: |
            cd hmpps-vsip-ui-tests
            mvn -f pom.xml clean install -Dmaven.test.skip=true
      - run:
          name: Change to project directory and run tests
          command: |
            cd hmpps-vsip-ui-tests
            mvn test -Dbrowser=remote-chrome -Denvironment="STAGING" -Dtest=uk.gov.justice.digital.hmpps.vsip.suites.RunOSSmokeTest
  acceptance_tests_develop:
    docker:
      - image: maven:3.9.5-eclipse-temurin-21
      - image: seleniarm/standalone-chromium
        environment:
          CHROME_HEADLESS: 1
    circleci_ip_ranges: true

    steps:
      - run:
          name: Checkout VSIP UI Tests
          command: git clone https://github.com/ministryofjustice/hmpps-vsip-ui-tests.git
      - run:
          name: get git status
          command: |
            cd hmpps-vsip-ui-tests
            git checkout develop
            git pull
            git status
      - run:
          name: Change to project directory then clean install
          command: |
            cd hmpps-vsip-ui-tests
            mvn -f pom.xml clean install -Dmaven.test.skip=true
      - run:
          name: Change to project directory and run tests
          command: |
            cd hmpps-vsip-ui-tests
            mvn test -Dbrowser=remote-chrome -Denvironment="STAGING" -Dtest=uk.gov.justice.digital.hmpps.vsip.suites.RunOSSmokeTest
  validate:
    executor:
      name: hmpps/localstack
      jdk_tag: "21.0"
      localstack_tag: "1.3"
    steps:
      - checkout
      - hmpps/wait_till_ready
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_multiplatform_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - validate
            - build_docker
            - helm_lint
      - request-staging-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_staging
          env: "staging"
          context:
            - hmpps-common-vars
            - hmpps-manage-prison-visits-orchestration-stage
          requires:
            - request-staging-approval
      - request-acceptance-tests-approval:
          type: approval
          requires:
            - deploy_staging
      - acceptance_tests_main:
          requires:
            - request-acceptance-tests-approval
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_staging
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          context:
            - hmpps-common-vars
            - hmpps-manage-prison-visits-orchestration-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          slack_notification: true
          slack_channel_name: << pipeline.parameters.releases-slack-channel >>
          context:
            - hmpps-common-vars
            - hmpps-manage-prison-visits-orchestration-prod
          requires:
            - request-prod-approval

  build-test-deploy-develop-branch:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_multiplatform_docker:
          name: build_docker
          filters:
            branches:
              only:
                - develop
      - request-dev-approval:
          type: approval
          filters:
            branches:
              only:
                - develop
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - develop
          requires:
            - validate
            - build_docker
            - helm_lint
            - request-dev-approval
      - request-staging-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_staging
          env: "staging"
          context:
            - hmpps-common-vars
            - hmpps-manage-prison-visits-orchestration-stage
          requires:
            - request-staging-approval
      - request-acceptance-tests-approval:
          type: approval
          requires:
            - deploy_staging
      - acceptance_tests_develop:
          requires:
            - request-acceptance-tests-approval
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_staging
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          context:
            - hmpps-common-vars
            - hmpps-manage-prison-visits-orchestration-preprod
          requires:
            - request-preprod-approval
  security:
    triggers:
      - schedule:
          cron: "54 5 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - veracode-credentials
            - hmpps-common-vars
  security-weekly:
    triggers:
      - schedule:
          cron: "21 5 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - veracode-credentials
            - hmpps-common-vars

  daily-test-runs:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
