---
# Per environment values which override defaults in hmpps-manage-prison-visits-orchestration/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-manage-prison-visits-orchestration-preprod.prison.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    MANAGE_USERS_API_URL: https://manage-users-api-preprod.hmpps.service.justice.gov.uk
    VISIT-SCHEDULER_API_URL: https://visit-scheduler-preprod.prison.service.justice.gov.uk
    PRISON_API_URL: https://prison-api-preprod.prison.service.justice.gov.uk
    ALERTS_API_URL: https://alerts-api-preprod.hmpps.service.justice.gov.uk
    PRISONER_SEARCH_URL: https://prisoner-search-preprod.prison.service.justice.gov.uk
    PRISONER-CONTACT_REGISTRY_URL: https://prisoner-contact-registry-preprod.prison.service.justice.gov.uk
    PRISON-REGISTER_API_URL: https://prison-register-preprod.hmpps.service.justice.gov.uk
    WHEREABOUTS_API_URL: https://whereabouts-api-preprod.service.justice.gov.uk
    PRISON-VISIT-BOOKER-REGISTRY_API_URL: https://hmpps-prison-visit-booker-registry-preprod.prison.service.justice.gov.uk
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

generic-prometheus-alerts:
  alertSeverity: visits-alerts-nonprod
  sqsAlertsQueueNames:
    - "book-a-prison-visit-preprod-hmpps_prison_visits_event_queue"
    - "book-a-prison-visit-preprod-hmpps_prison_visits_event_dlq"
  sqsAlertsOldestThreshold: 1
  sqsAlertsTotalMessagesThreshold: 1
