---
# Per environment values which override defaults in hmpps-manage-prison-visits-orchestration/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-manage-prison-visits-orchestration-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
