---
# Per environment values which override defaults in hmpps-manage-prison-visits-orchestration/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-manage-prison-visits-orchestration-preprod.prison.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    VISIT-SCHEDULER_API_URL: https://visit-scheduler-preprod.prison.service.justice.gov.uk
    PRISON_API_URL: https://api-preprod.prison.service.justice.gov.uk
    PRISONER-OFFENDER_SEARCH_URL: https://prisoner-offender-search-preprod.prison.service.justice.gov.uk
    PRISONER-CONTACT_REGISTRY_URL: https://prisoner-contact-registry-preprod.prison.service.justice.gov.uk
    PRISON-REGISTER_API_URL: https://prison-register-preprod.hmpps.service.justice.gov.uk
    WHEREABOUTS_API_URL: https://whereabouts-api-preprod.service.justice.gov.uk/
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
