---
# Per environment values which override defaults in hmpps-manage-prison-visits-orchestration/values.yaml

generic-service:
  replicaCount: 4

  ingress:
    host: hmpps-manage-prison-visits-orchestration.prison.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    VISIT-SCHEDULER_API_URL: https://visit-scheduler.prison.service.justice.gov.uk
    PRISON_API_URL: https://api.prison.service.justice.gov.uk
    PRISONER-OFFENDER_SEARCH_URL: https://prisoner-offender-search.prison.service.justice.gov.uk
    PRISONER-CONTACT_REGISTRY_URL: https://prisoner-contact-registry.prison.service.justice.gov.uk
    PRISON-REGISTER_API_URL: https://prison-register.hmpps.service.justice.gov.uk
    WHEREABOUTS_API_URL: https://whereabouts-api.service.justice.gov.uk
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  namespace_secrets:
    sqs-prison-visits-event-secret:
          HMPPS_SQS_QUEUES_PRISONVISITSEVENTS_QUEUE_NAME: "sqs_queue_name"
          HMPPS_SQS_QUEUES_PRISONVISITSEVENTS_QUEUE_ACCESS_KEY_ID: "access_key_id"
          HMPPS_SQS_QUEUES_PRISONVISITSEVENTS_QUEUE_SECRET_ACCESS_KEY: "secret_access_key"
    sqs-prison-visits-event-dlq-secret:
        HMPPS_SQS_QUEUES_PRISONVISITSEVENTS_DLQ_NAME: "sqs_queue_name"
        HMPPS_SQS_QUEUES_PRISONVISITSEVENTS_DLQ_ACCESS_KEY_ID: "access_key_id"
        HMPPS_SQS_QUEUES_PRISONVISITSEVENTS_DLQ_SECRET_ACCESS_KEY: "secret_access_key"

generic-prometheus-alerts:
  alertSeverity: prison-visit-booking-alerts
  sqsAlertsQueueNames:
    - "Digital-Prison-Services-prod-hmpps_prison_visits_event_queue"
    - "Digital-Prison-Services-prod-hmpps_prison_visits_event_dlq"
  sqsAlertsOldestThreshold: 1
  sqsAlertsTotalMessagesThreshold: 1
